fix: this patches the strEndsWith test case
Unleash/client-specification pull request #47
Opened 2023-01-25 17:22 UTC by sighphyre

The strEndsWith test case was previously checking that @some-email.com ends with @some-email.com. This means that an incorrectly implemented SDK could check that the context property ended with the constraint property and still pass the specifications. 

This patches that behaviour, meaning that dependent SDKs will now fail that test case correctly if the implementation is incorrect.

2023-01-25 19:07 UTC, ivarconr approved these changes

2023-01-25 19:09 UTC, ivarconr requested changes
Maybe also change the test cases to use actual email addresses, to be a more realistic example?
 
https://github.com/Unleash/client-specification/blob/756bccf8f2ba2cc408bd2d800624fec893f2fb09/specifications/13-constraint-operators.json#L451-L515

2023-01-26 07:15 UTC, sighphyre commented
> Maybe also change the test cases to use actual email addresses, to be a more realistic example?

Good suggestion! I've updated the tests to have a somewhat realistic email

2023-01-26 07:16 UTC, sighphyre commented
> Maybe also change the test cases to use actual email addresses, to be a more realistic example?

Good suggestion! I've updated the tests to have a somewhat realistic email

2023-01-31 08:25 UTC, ivarconr approved these changes

2023-01-31 08:35 UTC, merged